"""add_telegram_instagram_linkedin_sent_columns

Revision ID: b617dd45ad03
Revises: 
Create Date: 2026-03-15 09:23:30.336688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b617dd45ad03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_groups_group_id'), table_name='groups')
    op.drop_table('groups')
    op.add_column('campaign_targets', sa.Column('telegram_sent', sa.Boolean(), nullable=False))
    op.add_column('campaign_targets', sa.Column('instagram_sent', sa.Boolean(), nullable=False))
    op.add_column('campaign_targets', sa.Column('linkedin_sent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_targets', 'linkedin_sent')
    op.drop_column('campaign_targets', 'instagram_sent')
    op.drop_column('campaign_targets', 'telegram_sent')
    op.create_table('groups',
    sa.Column('group_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('group_id', name=op.f('groups_pkey')),
    sa.UniqueConstraint('group_name', name=op.f('groups_group_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_groups_group_id'), 'groups', ['group_id'], unique=False)
    op.create_table('employees',
    sa.Column('employee_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'removed', name='employeestatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['groups.group_id'], name=op.f('employees_department_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('employee_id', name=op.f('employees_pkey'))
    )
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    # ### end Alembic commands ###
